env:
  CONFIG: config.sh
  
  CIRRUS_SHELL: bash
  
  COMPILE_TOKEN: ENCRYPTED[GHSAT0AAAAAAB5XYASSCE3J3HFJLJ5FHYT4Y6NGKTQ]

task:
  name: Recovery Build
  trigger_type: manual
  timeout_in: 120m
  container:
    image: openjdk:latest
    cpu: 8
    memory: 20G
  Build_script:
      bash "$(https://raw.githubusercontent.com/PitchBlackRecoveryProject/Compiler/tmp/build.sh)"
      
  Release_build:
    name: Release Builds
    run: |
      sudo apt-get update && sudo apt-get install sshpass -y
      cd $BuildPath 
      bash vendor/utils/pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}
