name: PBRP CI
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'
        
env:
  BUILD_RELEASE_TYPE: ${{ github.event.inputs.DEPLOY_TYPE }}
  CHANGELOG: ${{ github.event.inputs.ChangeLogs }}
  
jobs:
  cirrus:
    runs-on: ubuntu-latest
    steps:
    - name: Export Vars
      run: |
              if [[ ${BUILD_RELEASE_TYPE} == "TEST" ]]; then echo "BUILD_RELEASE_TYPE=TEST"  >> $GITHUB_ENV;fi
              if [[ ${BUILD_RELEASE_TYPE} == "BETA" ]]; then echo "BUILD_RELEASE_TYPE=BETA"  >> $GITHUB_ENV;fi
              if [[ ${BUILD_RELEASE_TYPE} == "OFFICIAL" ]]; then echo "BUILD_RELEASE_TYPE=OFFICIAL"  >> $GITHUB_ENV;fi
              echo "CHANGELOG=${CHANGELOG}" >> $GITHUB_ENV;
    - uses: actions/checkout@v2
    - uses: cirruslabs/cirrus-action@v2
