name: PBRP CI
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'
        
env:
  BUILD_RELEASE_TYPE: ${{ github.event.inputs.DEPLOY_TYPE }}
  CHANGELOG: ${{ github.event.inputs.ChangeLogs }}
  
jobs:
  cirrus:
    runs-on: ubuntu-latest
    steps:
    - name: Sending variables to CIRRUS CI ENV
      run: |
           if [[ "$BUILD_RELEASE_TYPE" == "TEST" ]]; then 
           sed -i "16 c\     TEST_BUILD: true" https://raw.githubusercontent.com/PitchBlackRecoveryProject/android_device_oneplus_avicii-pbrp/cirrus_check/.cirrus.yml
           fi
           if [[ "$BUILD_RELEASE_TYPE" == "BETA" ]]; then 
           sed -i "16 c\     BETA_BUILD: true" https://raw.githubusercontent.com/PitchBlackRecoveryProject/android_device_oneplus_avicii-pbrp/cirrus_check/.cirrus.yml
           fi
           if [[ "$BUILD_RELEASE_TYPE" == "OFFICIAL" ]]; then 
           sed -i "16 c\     PB_OFFICIAL: true" https://raw.githubusercontent.com/PitchBlackRecoveryProject/android_device_oneplus_avicii-pbrp/cirrus_check/.cirrus.yml
           fi
           sed -i "17 c\     CHANGELOG: ${CHAGELOG}" https://raw.githubusercontent.com/PitchBlackRecoveryProject/android_device_oneplus_avicii-pbrp/cirrus_check/.cirrus.yml
      
    - uses: actions/checkout@v2
    - uses: cirruslabs/cirrus-action@v2
      
